version: "3.0"
services:
  generic-translator:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "Wohn.io Device Command Translator"
      MODULE_TYPE: "Processing"
      EGRESS_URLS: "https://testdockercompose.free.beeceptor.com"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      RUN_AS_STANDALONE: 'yes'
    ports:
      - 80:80